routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

//Route::get('home', function () {
//    return response('Hello World', 200)
//        ->header('Content-Type', 'text/plain');
//});
Route::get('brands', function (){

});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'MainController@index')->name('mains');
Route::middleware(['auth'])->group(function () {

    Route::resource('brands', 'BrandController');
    Route::resource('parentCs', 'ParentController');
    Route::resource('childCs', 'ChildController');
    Route::resource('products' , 'ProductController');

});

app/Brand.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Brand extends Model
{
    //
    use SoftDeletes;
    protected $fillable = [
        'name'
    ];

    protected $dates = ['deleted_at'];
}

app/Http/Controllers/BrandController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Brand;
use Validator;

class BrandController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

            $brands = Brand::get();
            return view('brands.index', ['brands' => $brands]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('brands.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $brand = Brand::create([
            'name' => $request->input('name')
        ]);
//            if ($brand){
//                return redirect()->route('brands.show', ['brand'=>$brand->id])->with('success', 'Brand create successfully');
//            }
        if ($brand) {
            return redirect('brands/' . $brand->id)->withErrors($brand)->withInput();
        }
    }

//
//    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Brand $brand)
    {
        $brand = Brand::findOrFail($brand->id);

        return view('brands.show', ['brand'=>$brand]);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Brand $brand)
    {
        $brand = Brand::find($brand->id);

        return view('brands.edit',['brand'=>$brand]);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Brand $brand)
    {
        $brandUpdate = Brand::where('id', $brand->id)
            ->update([
                'name' => $request->input('name'),
            ]);
        if ($brandUpdate){
            return redirect()->route('brands.show', ['brand'=>$brand->id]);
        }
        return back()->withInput();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Brand $brand)
    {
        //
        $findBrand = Brand::find( $brand->id);

        if ($findBrand->delete()){
            return redirect()->route('brands.index')->with('success', 'Brand have id  deleted success');
        }

        return back()->withInput()->with('error' , 'Brand could not be deleted');
    }
}

resources/views/brands/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-body">
                <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

                    <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
                        <h1>Create New Brand</h1>
                        <form action="{{ route('brands.store') }}" method="post">
                            {{ csrf_field() }}


                            <div class="form-group">
                                <lable for="brand-name">Name <span class="text-danger">*</span></lable>
                                <input placeholder="Enter name"
                                       id="brand-name"
                                       required
                                       name="name"
                                       spellcheck="false"
                                       class="form-control"
                                >
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary pull-right" value="submit">
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
                    <div class="sidebar-module">
                        <h4>Action</h4>
                        <ol class="list-unstyled">
                            <li><a href="/brands">My Brands</a></li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/brands/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-body">
                <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

                    <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
                        <h1>Edit Brand</h1>
                        <form action="{{ route('brands.update', $brand->id) }}" method="post">
                            {{ csrf_field() }}

                            {{ method_field('PUT')  }}
                            <div class="form-group">
                                <lable for="brand-name">Name <span class="text-danger">*</span></lable>
                                <input placeholder="Enter name"
                                       id="brand-name"
                                       required
                                       name="name"
                                       spellcheck="false"
                                       class="form-control"
                                       value="{{ $brand->name }}"
                                >
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary pull-right" value="submit">
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
                    <div class="sidebar-module">
                        <h4>Action</h4>
                        <ol class="list-unstyled">
                            <li><a href="/brands">My brands</a></li>

                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/brands/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-heading">Brand <a  class="pull-right btn btn-primary btn-xs" href="/brands/create">Create New</a></div>
            <div class="panel-body">
                <table class="table table-bordered table-striped table-auto table-condensed">
                    <thead class="panel-title">
                    <th class="text-center">Brand Name</th>
                    <th class="text-center">Detail</th>
                    </thead>
                    <tbody>

                    @foreach($brands as $brand)

                    <tr>
                        <td class="text-center">{{ $brand->name }}</td>
                        <td class="text-center"><a href="/brands/{{ $brand->id }}" class="btn btn-xs btn-success"><span class="glyphicon glyphicon-info-sign "></span></a></td>
                    </tr>

                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection

resources/views/brands/show.blade.php
@extends('layouts.app')

@section('content')


    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary ">
            <div class="panel-body">
                <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
                    <div class="col-md-9 col-lg-9 col-sm-9 pull-left">

                        <div class="jumbotron">
                            <h1>{{ $brand->name }}</h1>
                        </div>

                    </div>

                    <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
                        <div class="sidebar-module">
                            <h4>Action</h4>
                            <ol class="list-unstyled">
                                <li><a href="/brands/{{ $brand->id }}/edit">Edit</a></li>
                                <br>
                                <li>
                                    <a href="#"
                                       onclick="
                                            var result = confirm('Are you sure you wish to delete this Project?');
                                            if(result)
                                            {
                                            event.preventDefault();
                                            document.getElementById('delete-form').submit();
                                            }
                                            "
                                    >
                                        Delete
                                    </a>
                                    <form id="delete-form" action="{{ route('brands.destroy',[$brand->id]) }}"
                                          method="post" style="display: none;">
                                        <input type="hidden" name="_method" value="delete">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ol>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection