routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

//Route::get('home', function () {
//    return response('Hello World', 200)
//        ->header('Content-Type', 'text/plain');
//});
Route::get('brands', function (){

});
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'MainController@index')->name('mains');
Route::middleware(['auth'])->group(function () {

    Route::resource('brands', 'BrandController');
    Route::resource('parentCs', 'ParentController');
    Route::resource('childCs', 'ChildController');
    Route::resource('products' , 'ProductController');

});

app/ChildC.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ChildC extends Model
{
    //
    use SoftDeletes;
    protected $table = 'childC';

    protected $fillable = [
        'name',
        'parent_name'
    ];

    public function getParent()
    {
        return $this->belongsTo('App\ParentC', 'parent_name');
    }
    protected $dates = ['deleted_at'];

}

resources/views/childCs/create.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-body">
            <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
                <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px;">
                    <h1>Create New Child Category</h1>
                    <form action="{{ route('childCs.store') }}" method="post">
                        {{ csrf_field() }}

                        <div class="form-group">
                            <label for="childC-name">Name <span class="text-danger">*</span></label>
                            <input placeholder="Enter Name"
                                   id="childC-name"
                                   required
                                   name="name"
                                   spellcheck="false"
                                   class="form-control"
                            >
                        </div>
                        <div class="form-group">
                            <label for="parent-name">Parent Name <span class="text-danger">*</span></label>
                            <select  class="form-control" name="parent_name" id="parent-name" required spellcheck="false" >
                                @foreach($parentC as $value)

                                    <option value="{{ $value->id }}">{{ $value->name }}</option>

                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="submit" class="btn btn-primary pull-right" value="submit">
                        </div>
                    </form>

                </div>
            </div>

            <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
                <div class="sidebar-module">
                    <h4>Action</h4>
                    <ol class="list-unstyled">
                        <li><a href="/childCs">My Childs Category</a></li>
                    </ol>
                </div>
            </div>
        </div>
    </div>

    @endsection

resources/views/childCs/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-lg-offset-3 col-lg-offset-3">
        <div class="panel panel-primary">
            <div class="panel-body">
                <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
                    <div class="row col-md-12 col-lg-12 col-sm-12" style="background: white; margin: 10px">
                        <h1>Edit Child Category</h1>
                        <form action="{{ route('childCs.update', $childC->id) }}" method="post">
                            {{ csrf_field() }}

                            {{ method_field('PUT') }}
                            <div class="form-group">
                                <label for="childC-name">Child Category Name <span class="text-danger">*</span></label>
                                <input placeholder="Enter name"
                                       id="childC-name"
                                       required
                                       name="name"
                                       spellcheck="false"
                                       class="form-control"
                                       value={{ $childC->name }}
                                >
                            </div>
                            <div class="form-group">
                                <label for="parentC-name">Parent Category Name</label>
                                <select class="form-control" name="parent_name" id="parentC-name" >
                                    @foreach($parentC as $value)

                                        <option value="{{ $value->id }}">{{ $value->name }}</option>

                                        @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <input type="submit" class="btn btn-primary pull-right" value="submit">
                            </div>
                        </form>
                    </div>
                </div>

                <div class="col-sm-3 col-md-3 col-lg-3 pull-right">
                    <div class="sidebar-module">
                        <h4>Action</h4>
                        <ol class="list-unstyled">
                            <li><a href="/childCs">My Child Category</a></li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/childCs/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">Child Category <a href="/childCs/create" class="pull-right btn btn-primary btn-xs">Create New</a></div>
            <div class="panel-body">
                <table class="table table-bordered table-auto">
                    <thead class="panel-title">
                        <th class="text-center">Child Category Name</th>
                        <th class="text-center">Parent Category Name</th>
                        <th class="text-center">Detail</th>
                    </thead>
                    <tbody>

                    @foreach($childCs as $childC)

                        <tr>
                            <td class="text-center">{{ $childC->name }}</td>
                            <td class="text-center">{{ $childC->getParent->name }}</td>
                            <td class="text-center"><a href="/childCs/{{ $childC->id }}" class="btn btn-success btn-xs"><span class="glyphicon glyphicon-info-sign "></span></a></td>
                        </tr>

                        @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>

    @endsection

resources/views/childCs/show.blade.php
@extends('layouts.app')



@section('content')

    <div class="col-md-6 col-lg-6 col-md-offset-3 col-lg-offset-3">
        <div class="panel panel-primary">
            <div class="panel-body">
                <div class="col-md-9 col-lg-9 col-sm-9 pull-left">
                    <div class="col-md-10 col-lg-10 col-sm-10 pull-left">
                        <div class="jumbotron">
                            <table class="table table-borderedb table-condensed">
                                <thead class="panel panel-primary panel-title">
                                    <th class="text-center">Parent Category</th>
                                    <th class="text-center">Child Category</th>
                                </thead>

                                <tbody>
                                    <tr>
                                        <td class="text-center">{{ $childC->name }}</td>
                                        <td class="text-center">{{ $childC->getParent->name }}</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="col-md-2 col-lg-2 col-sm-2 pull-right">
                        <div class="sidebar-module">
                            <h4>Action</h4>
                            <ol class="list-unstyled">
                                <li><a href="/childCs/{{ $childC->id }}/edit">Edit</a></li>
                                <br>
                                <li><a href="#"
                                       onclick="
                                            var result = confirm('Are you sure you wish to delete this child category?');
                                            if (result)
                                                {
                                                    event.preventDefault();
                                                    document.getElementById('delete-form').submit();
                                                }
                                       "
                                    >Delete</a>
                                    <form id="delete-form" action="{{ route('childCs.destroy', [$childC->id]) }}" method="post" style="display: none">
                                        {{ method_field('DELETE')  }}
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @endsection